Repository 2024TUKCOMSP/forever, pull requests merged in 2024-07, with the labels that each got.

#34 feat : make project
  forever_planner/package-lock.json
  forever_planner/package.json
  forever_planner/src/App.vue
  forever_planner/src/components/Calendar/Date.vue
  forever_planner/src/main.js
  forever_planner/src/router/index.js
  forever_planner/src/views/CalendarView.vue
  forever_planner/src/views/HomeView.vue
  forever_planner/tailwind.config.js
Labels: enhancement

#37 feat : calendar page prototype
  forever_planner/src/components/Calendar/CalendarVue.vue
  forever_planner/src/components/Calendar/Date.vue
  forever_planner/src/components/Calendar/DateVue.vue
  forever_planner/src/components/Calendar/FinishiedPostVue.vue
  forever_planner/src/components/Calendar/PostVue.vue
  forever_planner/src/components/Calendar/WeekVue.vue
  forever_planner/src/views/CalendarView.vue
  forever_planner/tailwind.config.js
Labels: enhancement

#38 feat : make footer
  forever_planner/package-lock.json
  forever_planner/package.json
  forever_planner/src/App.vue
  forever_planner/src/components/Calendar/CalendarPage.vue
  forever_planner/src/components/FooterVue.vue
  forever_planner/src/main.js
  forever_planner/src/stores/store.js
  forever_planner/src/views/CalendarView.vue
Labels: enhancement

#40 feat : calendar modal
  forever_planner/src/App.vue
  forever_planner/src/components/Calendar/DateModal.vue
  forever_planner/src/components/Calendar/DateVue.vue
  forever_planner/src/components/Calendar/ModalFinishedPostVue.vue
  forever_planner/src/components/Calendar/ModalPostVue.vue
  forever_planner/src/components/FinishiedPostVue.vue
  forever_planner/src/components/FooterVue.vue
  forever_planner/src/router/index.js
  forever_planner/src/stores/modalStore.js
  forever_planner/src/views/HomeView.vue
  forever_planner/src/views/SettingView.vue
Labels: enhancement

#47 feat : make category page
  forever_planner/src/App.vue
  forever_planner/src/components/Calendar/Category/CategoryAddVue.vue
  forever_planner/src/components/Calendar/Category/CategoryEditVue.vue
  forever_planner/src/components/Calendar/Category/CategoryModal.vue
  forever_planner/src/components/Calendar/Category/CategoryVue.vue
  forever_planner/src/components/Calendar/DateModal.vue
  forever_planner/src/router/index.js
  forever_planner/src/stores/modalStore.js
  forever_planner/src/views/CalendarView.vue
  forever_planner/src/views/CategoryView.vue
Labels: enhancement

#52 feat : make post category
  forever_planner/src/components/Calendar/Category/CategoryModal.vue
  forever_planner/src/components/Calendar/Category/PostCategory.vue
  forever_planner/src/components/Calendar/Category/PostCategoryModal.vue
  forever_planner/src/components/Calendar/ConfirmModal.vue
  forever_planner/src/components/Calendar/DateModal.vue
  forever_planner/src/components/Calendar/Post/PostModal.vue
  forever_planner/src/stores/modalStore.js
  forever_planner/src/stores/store.js
  forever_planner/src/views/CalendarView.vue
  forever_planner/src/views/CategoryView.vue
Labels: bug, enhancement

#53 자잘하게 수정, home쪽에 scroll method import
  forever_planner/src/views/HomeView.vue
  forever_planner/src/views/RemainingTodoView.vue
  forever_planner/src/views/SettingView.vue
Labels: bug

#62 feat : link api
  forever_planner/package-lock.json
  forever_planner/package.json
  forever_planner/src/components/Calendar/CalendarPage.vue
  forever_planner/src/components/Calendar/Category/CategoryAddVue.vue
  forever_planner/src/components/Calendar/Category/CategoryEditVue.vue
  forever_planner/src/components/Calendar/Category/CategoryModal.vue
  forever_planner/src/components/Calendar/Category/CategoryVue.vue
  forever_planner/src/components/Calendar/DateModal.vue
  forever_planner/src/components/Calendar/DateVue.vue
  forever_planner/src/components/Calendar/Post/FinishedPostVue.vue
  forever_planner/src/components/Calendar/Post/ModalFinishedPostVue.vue
  forever_planner/src/components/Calendar/Post/ModalPostVue.vue
  forever_planner/src/components/Calendar/Post/PostCalendar.vue
  forever_planner/src/components/Calendar/Post/PostModal.vue
  forever_planner/src/components/Calendar/Post/PostVue.vue
  forever_planner/src/components/Theme/ThemeVue.vue
  forever_planner/src/stores/modalStore.js
  forever_planner/src/stores/store.js
  forever_planner/src/views/CalendarView.vue
  forever_planner/src/views/ThemeView.vue
Labels: enhancement

#65 feat : link api
  forever_planner/src/components/Calendar/DateModal.vue
  forever_planner/src/components/Calendar/DateVue.vue
  forever_planner/src/components/Calendar/Post/ModalPostVue.vue
  forever_planner/src/components/Calendar/Post/PostCalendar.vue
  forever_planner/src/components/Calendar/Post/PostModal.vue
  forever_planner/src/components/Calendar/Post/PostVue.vue
  forever_planner/src/components/Theme/ThemeVue.vue
  forever_planner/src/stores/modalStore.js
  forever_planner/src/stores/store.js
  forever_planner/src/views/ThemeView.vue
Labels: enhancement

#69 feat : link api
  forever_planner/src/components/Calendar/Category/CategoryModal.vue
  forever_planner/src/components/Calendar/Category/PostCategory.vue
  forever_planner/src/components/Calendar/Category/PostCategoryModal.vue
  forever_planner/src/components/Calendar/ConfirmModal.vue
  forever_planner/src/components/Calendar/DateVue.vue
  forever_planner/src/components/Calendar/Post/PostModal.vue
  forever_planner/src/stores/modalStore.js
  forever_planner/src/stores/store.js
  forever_planner/src/views/CategoryView.vue
Labels: enhancement
